[package]
name = "playback-formatter"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
cmus-status-line = { branch = "master", git = "https://github.com/Noah2610/cmus-status-line" }
